#ifndef CAR_MODEL_HANDLING_DEF_H_FILE
#define CAR_MODEL_HANDLING_DEF_H_FILE

#include "SlfBase.h" 

#define CAR_MODEL_ERROR_NR_PARAMETR_FILE_NOT_READ 1
#define CAR_MODEL_ERROR_NR_PARAMETR_STRING_NOT_READ 2

#endif //CAR_MODEL_HANDLING_DEF_H_FILE